### ISSUE TITLE
MLFriends

### ISSUE THREAD

**Issue by JohannesBuchner** [joshspeagle/dynesty#121]
Hi Josh,

I wrote a new implementation of MLFriends (learning the scales of the space), and tried to adhere to dynesty coding style. I believe the solution is quite compact:

https://github.com/JohannesBuchner/dynesty/commit/5d6edb35c89bb7d7d887c72186ed8c34eb7de7ff

Already for a simple gaussian likelihood on a unit cube::

```
   scales = np.array([0.1, 0.001, 0.3])
   def loglike(x):
       return -0.5 * (((x - 0.5) / scales)**2).sum()
```

The speed-up from simply normalising each axis is already a factor of 4.

The efficiency improvement will be arbitrarily high when scales[1] is set to any lower value.

The reference for this variant of RadFriends is https://arxiv.org/abs/1707.04476 (just mentioned in a sentence).

In Radfriends it is also natural to define clusters of balls. Avoiding a scaling across ball clusters, and using intra-cluster scales further improves results in multimodal distributions.

The following likelihood:

```
  scales = np.array([0.1, 0.001, 0.3])
  mu1 = np.array([0.3, 0.2, 0.3])
  mu2 = np.array([0.3, 0.4, 0.3])
  def loglike(x):
      l1 = -0.5 * (((x - mu1) / scales)**2).sum()
      l2 = -0.5 * (((x - mu2) / scales)**2).sum()
      return np.logaddexp(l1, l2)
```

Then sees another factor of 4 increase in efficiency, and again arbitrarily higher with cluster size to cluster distance increases.

I believe including this would be useful for users of dynesty.

**Comment by joshspeagle** [comment]
I'm always happy to add in alternate implementations. I don't think I'll have time to get to this before I submit/release the paper on arxiv and will be traveling for the next two weeks, but I'll try to add this in when I get the chance for users who are't satisfied with ellipsoids :).

**Comment by joshspeagle** [comment]
Hey Johannes,

Looking through your implementation in detail I agree this is actually a really nice place to start and an elegant implementation. I think the use of mean-centering from clustering is a good approach for dealing with multi-modal distributions. The failure to account for different behavior between the modes (i.e. assuming they are similarly shaped) is inherent to having a global metric for the ensemble relative to using multiple ellipsoids of varying sizes and shapes, so there's not much you can do about it without fancier changes.

If it's alright with you, I'd like to incorporate this solution directly into `balls` and `cubes` following your outline with two main changes:
1. I want to try using the Mahalanobis distance to account for covariance structure, rather than the marginal correlations in each dimension. This involves a bit more work in terms of getting the cholesky decomposition for `csqrt` and using einsum-style math to do the dot products quickly when transforming points, but should be quite doable (timing tests I ran as part of #115 suggest this can be surprisingly fast).
2. I'd like to incorporate this as a flag that gets passed to `RadFriends` and `SupFriends`, which then triggers whether `_get_axscale_from_clusters` is called (or defaults to `np.ones` and gives `csqrt = np.identity`).

Does that framework sound reasonable to you?

**Comment by JohannesBuchner** [comment]
Sure, that sounds reasonable. Two general tips:

* RadFriends from the original paper is an algorithm where one can choose the distance metric, which gives various special cases. L1 is SupFriends, Euclidean is RadFriends, determination of the metric during the run I call metric learning friends (MLFriends, last paper).
* Working on the latest, I looked into 
  * Standardized Euclidean distance
  * Mahalanobis distance
  * SDML from https://github.com/metric-learn/metric-learn

  I didn't manage to get SDML running properly, and the Mahalanobis distance seemed a bit noisy (because ~n²/2 parameters to learn). Combined with unrelated reasons I ended up preferring a Standardized Euclidean.

If you can get the Mahalanobis distance running, great! Already Standardized Euclidean is a great performance boost. 

I will add a pull request, you can merge it and adjust.

**Comment by joshspeagle** [comment]
> RadFriends from the original paper is an algorithm where one can choose the distance metric, which gives various special cases.

Right, I remember experimenting with allowing the Lp norms to change and not finding much improvement. Also, I think the Lsup norm is actually SupFriends (L2 sphere is inscribed in Lsup cube), while L1 gives the Manhattan distance (L1 cube is inscribed in L2 sphere). Given that L1 and Lsup are both cubes (but one is rotated relative to the axes), I don't think the difference matters that much though.

> the Mahalanobis distance seemed a bit noisy 

Yea, that noise ends up impacting the ellipsoids as well (and is usually worse since they don't use all the live points) and led to a host of issues when I tried to regularize them to prevent this (see #99). Given that ensemble approaches generally should be running with `nlive >> d^2/2` points though, I think this might be alright.

**Comment by JohannesBuchner** [comment]
You are of course right, my too-quick lookup failed me (it's even in the name too ;) ).

**Comment by joshspeagle** [comment]
@JohannesBuchner I ran some tests with the Mahalanobis implementation I added in to check nothing crazy was going on, but it could always use more stress tests. Let me know what you think of the implementation and if you discover any bugs in what you're interested in building.
