### ISSUE TITLE
API/example for obtaining unweighted posterior samples

### ISSUE THREAD

**Issue by segasai** [joshspeagle/dynesty#125]
Hi, 

I was looking at the docs, and I couldn't see an *official* way of getting unweighted posterior samples out the nested sampler run. Looking at the plotting routines, as far as I can see the way to get them is like that:
```
NS = dynesty.NestedSampler(like,prior,ndim=10)
NS.run_nested()
wht=np.exp(NS.results['logwt']-NS.results['logz'][-1])
samps = dynesty.utils.resample_equal(NS.results.samples,wht)
```
If I am correct, it may be worth having a simple function that just takes a results object and returns an unweighted samples, as it wasn't immediately obvious to me, where the correct weights are stored. If adding a function is not an option, maybe having an example in the docs would be good (unless I just missed it).

Thanks!

**Comment by joshspeagle** [comment]
I actually have this as an example in the “Crash Course” section along with a few other post-processing examples, but I agree that I should probably add this in to the “Basic Post-Processing” sub-section of “Getting Started” as well, since I realized I don’t actually have a thorough description of those functions all in one place. 

As for why this doesn’t directly operate on the ‘results’ directly, it was generally to ensure backwards compatibility with earlier versions of the code. Hopefully it’s not too much of an inconvenience.

**Comment by segasai** [comment]
No problem. I apparently I missed the last section of the crash course. I just went from using pymultinest where the equally weighted posterior samples were immediately available, and was a bit puzzled for a while when I could find them in dynesty.
