### ISSUE TITLE
Derived parameters / blobs

### ISSUE THREAD

**Issue by joezuntz** [joshspeagle/dynesty#136]
Hi,

I couldn't see a way in the current code to save derived parameters that are computed alongside the likelihood ("blobs" in Emcee language).

Is there a way to do this?  If not I'd like to put this in as an enhancement request.

Cheers,
Joe

**Comment by joshspeagle** [comment]
I'm a little confused here. You had requested this previously in #98, and I commented there that it turns out the way I structured the code (i.e. not well) makes this straightforward feature request actually quite difficult to implement. I am happy to take a PR that could add this in if you want to take a crack at it, but for the time being do not plan on implementing this feature in `dynesty`. I hope to structure future samplers better to enable this functionality in the future.

**Comment by joezuntz** [comment]
Completely forgot that I'd asked this already - apologies!

Cheers,
Joe
