### ISSUE TITLE
adaptive sampling

### ISSUE THREAD

**Issue by jrleja** [joshspeagle/dynesty#16]
It might be useful to allow the sampling technique to vary during a fit as a function of efficiency (or in emcee parlance, 'acceptance fraction') and number of dimensions. For example, if the efficiency of a uniform sampler decreases to 10% or less in a high dimensional space, it would save time to switch to a slice sampler.

**Comment by joshspeagle** [comment]
Great idea -- I'll see if I can add this in once I get the other sampling methods put in place.

**Comment by joshspeagle** [comment]
Referenced issue incorrectly in (now overwritten) commit.

**Comment by joshspeagle** [comment]
After thinking about this a bit more, it's unclear *a priori* whether one sampling method will be more or less efficient at exploring the prior volume than another; the detailed efficiency properties depend primarily on the dimensionality of the space but also to some extent on the shape of the target distribution. While I could likely assign some rough criteria for switching from one to another (via rough dimensional scalings for `'rwalk'`, `'slice'` and `'rtraj'`), I personally think these other sampling methods are more useful when the distribution cannot be effectively bounded. This holds true (1) when the number of live points is small and (2) when the dimensionality of the problem is high (since the volume of bounding surfaces become increasingly concentrated near the boundaries). These seem to match the general framework of the (in progress) `DynamicSampler` better, so I think this type of adaptive sampling fits much more naturally there.

I guess my thinking is I don't think it's worth adding this feature natively into `NestedSampler` at the moment. However, given that I'll be putting in the framework to do very similar things with `DynamicSampler`, I might come back to this if it turns out to be a straightforward addition.
