### ISSUE TITLE
Removing a bottleneck from rwalk proposals with a parallel pool 

### ISSUE THREAD

**Issue by rory-smith** [joshspeagle/dynesty#164]
Hi Josh,

I'm experimenting with the performance of the rwalk sampler using a parallel pool and I've noticed that a bottle neck can occur when one or more processes can get stuck inside the `while` loop: 

https://github.com/joshspeagle/dynesty/blob/ab8c73c47fc6f468da719ead42cae5ac07af0a37/dynesty/sampling.py#L170

My understanding is that the mcmc sampling continues until a parameter-space point is found with a likelihood higher than the worst point. While this makes sense in "serial mode", this can cause a bottle neck "parallel mode" where a relatively large number of processes can end up waiting in a queue for a small number of processes to return a live point. In a worst case scenario where N-1 processes have returned a point, but one has not, we would be in a situation where we're waiting for a single process, at least doubling the time to return the set of N points. 

I was wondering if we could just remove`accept == 0` from the `while` loop and return *any* point from the mcmc process? This would return dud points for some processes, reducing the overall sampling efficiency, but as long as these points are always rejected it would mean that we're not always limited by the least-efficient rwalks in the pool.  I don't see any fundamental issue with doing this, but I'm not super familiar with the inner workings of dynesty so I just wanted to get your opinion on this to see if, e.g., it might introduce biases because of the way dynesty handles points returned by the sampling routine.

Best,
Rory

**Comment by joshspeagle** [comment]
This ties into some of the proposed changes in #163 in terms of making effective proposals from `rwalk`, which also makes changes somewhat along the lines you are suggesting. I'll come back to this after merging that in, since it may fix this problem anyways.

Theoretically-speaking, you're correct that the `accept == 0` condition is not necessary and we can return any point rather than just the last one. The issue with the `pool` is one that I knew would have to be addressed at some point since the default parallelization scheme uses a synchronous pool, so thanks for bringing this up. Hopefully it'll be resolved ~soon-ish now that I'm back from vacation.

**Comment by rory-smith** [comment]
Thanks for the update!

**Comment by rory-smith** [comment]
Thanks for the info!

**Comment by joshspeagle** [comment]
Didn't quite implement this, but I'll consider the recent changes fixing up the `rwalk` sampling behaviour to more or less resolve this.
