### ISSUE TITLE
Add handling of likelihood plateaus?

### ISSUE THREAD

**Issue by mattpitkin** [joshspeagle/dynesty#242]
Is anyone planning on implementing the handling of likelihood plateaus suggested in https://arxiv.org/abs/2010.13884? It looks like implementing their Algorithm 2 would be fairly simple and backwards compatible. I can give it a go if it's something that is wanted.

**Comment by joshspeagle** [comment]
Sorry for the delay in getting back to this. As far as I know, no one is currently planning on implementing this procedure. I think it's straightforward enough in theory (if the acceptance criterion is swapped back to `>=` instead of `>`), so if you'd like to tackle adding this in I'd definitely appreciate it!

**Comment by mattpitkin** [comment]
No problem. Hopefully I'll find some time to give this a go.
