### ISSUE TITLE
Dynamic Nested Sampler: Negative logzvar

### ISSUE THREAD

**Issue by bacook17** [joshspeagle/dynesty#31]
When running a test using the dynamic nested sampler, logzvar came out negative after a couple thousand iterations:

`  ^Mrun: 0 | iter: 1592 | nc: 1 | ncall: 50649 | eff(%):  3.145 | logz: -7747\
.346 +/-  0.219 | dlogz: 36.407 >  0.500    ^Mrun: 0 | iter: 1593 | nc: 1 | n\
call: 50650 | eff(%):  3.147 | logz: -7744.512 +/-  0.454 | dlogz: 33.439 >  \
0.500    ^Mrun: 0 | iter: 1594 | nc: 1 | ncall: 50651 | eff(%):  3.149 | logz\
: -7741.552 +/-  0.457 | dlogz: 30.325 >  0.500    ^Mrun: 0 | iter: 1595 | nc\
: 1 | ncall: 50652 | eff(%):  3.151 | logz: -7740.474 +/-  0.242 | dlogz: 29.\
065 >  0.500    Traceback (most recent call last):
  File "pcmd_integrate.py", line 55, in <module>
    results = fit_model.nested_integrate(**args)
  File "/n/home01/bcook/pixcmd/pcmdpy/fit_model.py", line 202, in nested_inte\
grate
    sampler.run_nested(ninit=N_points, maxcall_init=max_call, dlogz_init=dlog\
z)
  File "/n/home01/bcook/dynesty/dynesty/dynamicsampler.py", line 1099, in run\
_nested
    logzerr = math.sqrt(logzvar)
ValueError: math domain error

`

**Comment by joshspeagle** [comment]
This turns out to be an issue with the uncertainties on our `logzvar` approximation. These are based on the changes in information `h` normalized by the change in prior volume. During early stages of runs this can go negative. It can also go negative at the last step of runs when adding in the final live points -- since the final set of points uniformly span the prior volume, the errors in the change in volume can really explode if we stop relatively early. I've since changed to `np.sqrt` instead of `math.sqrt` to prevent this from killing runs since it's actually the correct behavior.
