### ISSUE TITLE
Question about specifying a tricky prior in the `loglike` function

### ISSUE THREAD

**Issue by Nicholaswogan** [joshspeagle/dynesty#370]
Thanks for the great package.

I'm using `dynesty` to compute posteriors of gas concentrations. I need to specify a prior which says that the sum of the gas concentrations must not exceed 1 ( a sum greater than 1 would be unphysical). This prior is hard to implement in the `prior_transform` function. 

Is it OK if I enforce this prior in the `loglike` function. If this prior is violated, I can return a very small log-likelihood, like `-100.0`.

Thanks!

**Comment by segasai** [comment]
Hi, 

First  you can incorporate that prior through prior_transform by doing a bit of reparametrisation. 
I.e. a >=0 b>=0 and a+b<1 
you can reparametrise it through f=a/(a+b) and r=a+b with the prior being r<1 and f<1

Second, because the dynesty samples the posterior, i.e. pi(\theta) L(\theta), it's always possible to represent it differently   pi(\theta) L(\theta)=pi*(\theta) L*(\theta) where L*(\theta) = L(\theta) * pi(\theta)/\pi*(\theta). This essentially allows you to adopt a different prior and adjust the likelihood, while have mathematically the same posterior

Thirdly, it is also fine to simply return really low valuesin the likelihood where the parameters don't make sense (I'd probably use something like -1e100). It may make the sampling a tad less efficient, but is fine mathematically.

**Comment by Nicholaswogan** [comment]
Thanks so much for the speedy response!

**Comment by segasai** [comment]
Sure, no problem. I'll close the issue now.
