### ISSUE TITLE
Questions about DynamicNestedSampler setting

### ISSUE THREAD

**Issue by gwwydru** [joshspeagle/dynesty#459]
Hi，
I'm currently using dynesty for a 10-dimensional sampling task, and the posterior results for most parameters look good. However, I consistently get incorrect results for two specific parameters. I'm currently using rslice with 40 slices, 2000 livepoints and balls as the bound. Could you please advise on how to adjust the settings to obtain the correct results?

This is the likelihood value for the x6, the red vertical dashed line is the truth and the blue one is the result of the sample. The x axis is value of parameter and the y axis is the value of likelihood.
![0 95](https://github.com/joshspeagle/dynesty/assets/150639921/9c59d74b-2a8d-4dbd-a013-f1738c5809c9)
this is the likelihood for x7
![ss](https://github.com/joshspeagle/dynesty/assets/150639921/6a972998-911f-425e-b9a6-8eb6ade73098)
and this is the traceplot of x6 and x7
![微信图片_20231113111304](https://github.com/joshspeagle/dynesty/assets/150639921/f9c1f852-2d2b-4825-9c3a-f408e916d59d)
And I also find that more livepoints seem to make the results worse, is there a way to determine the appropriate number of livepoints (or slice for rslice method)?

**Comment by segasai** [comment]
Hi, 

I think from your question it is not clear why you think it's a dynesty issue. 
I think there are two options here
* Dynesty fails to get a correct posterior
* There is an issue with the posterior itself.

I am happy to be convinced that it's the former, but you need to show why you think that. For example if you show that the logl value at true parameter values is higher (or comparable) to the maximum likelihood dynesty finds is a good proof.

Also, I don't know how to interpret the first two plots, and what the 1-D curved represent (i.e. are those slices of likelihood or what exactly).

**Comment by gwwydru** [comment]
Thanks for your reply. Sorry for the misuse of the issue. It is indeed the case that Dynesty fails to get a correct posterior. The logl valuefor the true parameter values is ~0, and for my dynesty run is loglstar:   -inf < -19.534 <    inf.

**Comment by segasai** [comment]
If the numbers you give are correct and logL_max_dynesty=-19 and logL(true_x)=0, that would likely indicate dynesty finding a narrow node in the posterior. 
Since you have not provided many details, such as 
* the code you use to run
* all the options
* dynesty version 
* corner plot of the results
* dynesty output
* evidence the posterior does peak at true_x 

I am not sure there much I can suggest, other then the main parameters helping with the discovery of multiple modes are the number of live-points. You can also adding manual nested runs  ( see #327 ) to see if that helps.

**Comment by gwwydru** [comment]
Thank you very much!
